# Base docker-compose configuration

    services:
      crowdsec:
        image: crowdsecurity/crowdsec:latest
        platform: linux/arm64/v8
        container_name: crowdsec
        restart: always
        environment:
          - GID=1000
        volumes:
          - /var/log/auth.log:/var/log/auth.log:ro
          - /var/log/syslog:/var/log/syslog:ro
          - ./config:/etc/crowdsec
          - ./data:/var/lib/crowdsec/data
        ports:
          - "8080:8080" # Local API port
